export const pageStyles = {
  main: 'min-h-screen bg-canvas pt-16 text-ink',
  section: 'bg-surface py-20',
  container: 'mx-auto max-w-7xl px-4 sm:px-6 lg:px-8',
  introduction: 'max-w-3xl space-y-4',
  paragraph: 'max-w-3xl leading-relaxed text-muted',
  sections: 'mt-12 space-y-12 border-t border-border-soft pt-12 sm:mt-16 sm:space-y-16 sm:pt-16',
  sectionTitle: 'mb-6 text-2xl font-bold text-ink',
  journey: 'max-w-3xl space-y-6 border-l-2 border-border-accent pl-6',
  journeyItem: 'leading-relaxed text-muted',
  prose: 'max-w-3xl space-y-4',
  steps: 'my-6 grid list-inside list-decimal gap-3 sm:grid-cols-2 lg:grid-cols-4',
  step: 'rounded-lg border border-border-soft bg-canvas p-4 leading-relaxed text-ink marker:font-bold marker:text-accent-strong',
  education: 'grid gap-6 md:grid-cols-2',
  card: 'min-w-0 rounded-lg border border-border-soft bg-canvas p-6',
  cardTitle: 'mb-4 text-lg font-bold text-ink',
  educationStatus: 'mb-3 text-sm font-medium text-accent-strong',
  growthIntroduction: 'mb-4 leading-relaxed text-muted',
  objective: 'mt-6 max-w-3xl border-l-2 border-border-accent pl-6 leading-relaxed text-ink',
  technologies: 'grid gap-6 sm:grid-cols-2 lg:grid-cols-3',
  bulletList: 'list-disc space-y-2 pl-5',
  columnsList: 'grid list-disc gap-x-10 gap-y-3 pl-5 md:grid-cols-2 lg:grid-cols-3',
  bulletItem: 'pl-1 leading-relaxed text-muted marker:text-accent-strong',
} as const;
