export const pageStyles = {
  main: 'min-h-screen bg-canvas pt-16',
  section: 'bg-surface py-20',
  container: 'mx-auto max-w-7xl px-4 sm:px-6 lg:px-8',
  emptyState: [
    'mx-auto max-w-2xl rounded-lg border border-border-soft bg-surface-soft p-8',
    'text-center text-muted',
  ].join(' '),
  list: 'grid gap-6',
  card: 'min-w-0 rounded-lg border border-border-soft bg-surface p-6 shadow-soft sm:p-10',
  role: 'text-xl font-bold text-ink',
  organization: 'mt-1 font-medium text-accent-strong',
  period: 'mt-1 text-sm text-muted',
  details: 'mt-6 space-y-8 border-t border-border-soft pt-6 sm:mt-8 sm:space-y-10 sm:pt-8',
  sectionTitle: 'text-lg font-bold text-ink',
  summary: 'mt-3 max-w-3xl space-y-3',
  description: 'leading-relaxed text-muted',
  items: 'mt-4 grid list-disc gap-x-10 gap-y-3 pl-5 md:grid-cols-2',
  item: 'pl-1 leading-relaxed text-muted marker:text-accent-strong',
  technologies: 'mt-4 flex flex-wrap gap-2',
} as const;
